export const defaultProjects = [
  {
    slug: "fidapp",
    title: "FidApp",
    year: "2025",
    status: "live",
    sector: "Fidélité · commerces marocains",
    sectorEn: "Loyalty · Moroccan retail",
    summary:
      "Le client scanne un QR, cumule des visites, sans installer d’app. Monorepo : PWA client, dashboard commerçant, admin, API — QR anti-fraude à rotation.",
    summaryEn:
      "Customers scan a QR, collect visits, no app install. Monorepo: client PWA, merchant dashboard, admin, API — rotating anti-fraud QR.",
    stack: "React · Node · PostgreSQL · Prisma · PWA",
    image: "/assets/shot-fidapp.png",
    problem:
      "Les commerces marocains perdent leurs clients fidèles faute de carte physique ou d’app à installer.",
    problemEn:
      "Moroccan shops lose repeat customers without a physical card or an app to install.",
    solution:
      "PWA + QR sans téléchargement, dashboard commerçant, admin, API, anti-fraude par rotation de codes.",
    solutionEn:
      "PWA + QR with no download, merchant dashboard, admin, API, anti-fraud via rotating codes.",
    result: "4 applications en production, utilisées au quotidien.",
    resultEn: "4 apps in production, used daily.",
    featured: true,
    published: true,
    sortOrder: 1,
  },
  {
    slug: "foodgroup-erp",
    title: "Entrepôt ERP/CRM — Food Group",
    year: "2025",
    status: "mission",
    sector: "Distribution · Dynamics 365 BC",
    sectorEn: "Distribution · Dynamics 365 BC",
    summary:
      "77 tables documentées à la main (ventes, stock, CRM, RH, finance), pipelines ETL et dashboards Power BI.",
    summaryEn:
      "77 tables documented by hand (sales, stock, CRM, HR, finance), ETL pipelines and Power BI dashboards.",
    stack: "SQL Server · n8n · Power BI · T-SQL",
    image: "",
    problem: "ERP/CRM peu documenté, reporting difficile.",
    problemEn: "Poorly documented ERP/CRM, hard reporting.",
    solution: "Structuration de 77 tables, ETL, Power BI sur Dynamics 365 BC.",
    solutionEn: "Structured 77 tables, ETL, Power BI on Dynamics 365 BC.",
    result: "Base claire pour les décisions métier.",
    resultEn: "Clear base for business decisions.",
    featured: false,
    published: true,
    sortOrder: 2,
  },
  {
    slug: "2rparts",
    title: "2R Parts",
    year: "2025",
    status: "prod",
    sector: "Pièces auto · desktop",
    sectorEn: "Auto parts · desktop",
    summary:
      "Caisse, stock, crédit client, fournisseurs, factures PDF — un logiciel Windows fait pour le comptoir.",
    summaryEn:
      "POS, stock, customer credit, suppliers, PDF invoices — Windows software made for the counter.",
    stack: "Python · PyQt5 · SQLite",
    image: "/assets/shot-2rparts.png",
    problem: "Gestion comptoir trop lente / Excel.",
    problemEn: "Counter ops too slow / Excel.",
    solution: "Application desktop POS + stock + facturation PDF.",
    solutionEn: "Desktop POS + stock + PDF invoicing.",
    result: "Livré et utilisé en production.",
    resultEn: "Shipped and used in production.",
    featured: false,
    published: true,
    sortOrder: 3,
  },
  {
    slug: "jobgate",
    title: "JobGate — studio vidéo",
    year: "2025",
    status: "mission",
    sector: "Recrutement",
    sectorEn: "Recruitment",
    summary:
      "Backend Django : entretiens vidéo WebRTC, auth multi-fournisseurs, candidatures et files Celery/Redis.",
    summaryEn:
      "Django backend: WebRTC video interviews, multi-provider auth, applications, Celery/Redis queues.",
    stack: "Django · WebRTC · PostgreSQL · Celery",
    image: "",
    problem: "Le CV seul ne suffit pas pour évaluer un candidat.",
    problemEn: "A CV alone is not enough to assess a candidate.",
    solution: "Studio d’entretien vidéo intégré + gestion candidatures.",
    solutionEn: "Integrated video interview studio + application management.",
    result: "Module backend livré pour la plateforme.",
    resultEn: "Backend module delivered for the platform.",
    featured: false,
    published: true,
    sortOrder: 4,
  },
  {
    slug: "optigest",
    title: "Opti Gest",
    year: "2025",
    status: "delivered",
    sector: "Optique · Windows / Mac",
    sectorEn: "Optics · Windows / Mac",
    summary:
      "Clients, ordonnances, devis, mutuelles CNOPS/CNSS, rappels WhatsApp — données en local (SQLite).",
    summaryEn:
      "Clients, prescriptions, quotes, CNOPS/CNSS mutuals, WhatsApp reminders — local SQLite data.",
    stack: "Electron · React · Express · Prisma",
    image: "/assets/shot-optigest.png",
    problem: "Magasin d’optique limité par Excel et process manuels.",
    problemEn: "Optics shop limited by Excel and manual processes.",
    solution: "App desktop locale avec mutuelles, devis et rappels.",
    solutionEn: "Local desktop app with mutuals, quotes and reminders.",
    result: "Logiciel livré pour le magasin.",
    resultEn: "Software delivered for the shop.",
    featured: false,
    published: true,
    sortOrder: 5,
  },
  {
    slug: "gpsi",
    title: "GPSI",
    year: "2025–26",
    status: "mission",
    sector: "Parc IT · Food Group",
    sectorEn: "IT fleet · Food Group",
    summary:
      "Inventaire équipements, tickets SLA, rôles admin/technicien/utilisateur, copilote IA local (Ollama).",
    summaryEn:
      "Asset inventory, SLA tickets, admin/tech/user roles, local AI copilote (Ollama).",
    stack: "Laravel · Inertia · React · PostgreSQL",
    image: "",
    problem: "Parc IT et tickets peu structurés.",
    problemEn: "IT fleet and tickets poorly structured.",
    solution: "Inventaire + SLA + rôles + copilote local.",
    solutionEn: "Inventory + SLA + roles + local copilote.",
    result: "MVP livré en mission interne.",
    resultEn: "MVP delivered on an internal mission.",
    featured: false,
    published: true,
    sortOrder: 6,
  },
  {
    slug: "gestipro",
    title: "GestiPro",
    year: "2026",
    status: "wip",
    sector: "SaaS multi-tenant · commerces",
    sectorEn: "Multi-tenant SaaS · retail",
    summary:
      "Plateforme pour restaurants, dépôts et boutiques : opérations du jour, stock, parcours métier — encore en construction.",
    summaryEn:
      "Platform for restaurants, warehouses, and shops: daily ops, stock, workflows — still under construction.",
    stack: "Next.js · Supabase · Vercel",
    image: "",
    problem: "Commerces sans outil multi-tenant unifié.",
    problemEn: "Shops without a unified multi-tenant tool.",
    solution: "SaaS multi-tenant en cours de construction.",
    solutionEn: "Multi-tenant SaaS under construction.",
    result: "En développement.",
    resultEn: "In development.",
    featured: false,
    published: true,
    sortOrder: 7,
  },
];
